### ISSUE TITLE
Installing on OSX fails

### ISSUE THREAD

**Issue by mitra42** [jronallo/iiif-image-server-node#3]
I'm not sure if this is still maintained as its a little old ... 
Install on OSX doesn't work - either with npm or yarn 

I'll post full log in first comment. 
Note - that I did install libvips with `brew install vips` which succeeded.

Something else i missed ?

**Comment by mitra42** [comment]
```
mitraglass:iiif-image-server-node mitra$ npm i
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated superagent@1.8.5: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.

> dtrace-provider@0.8.8 install /Users/mitra/git/iiif-image-server-node/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
starting .bashrc
  TOUCH Release/obj.target/ndtp.stamp

> fsevents@1.2.11 install /Users/mitra/git/iiif-image-server-node/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> sharp@0.16.2 install /Users/mitra/git/iiif-image-server-node/node_modules/sharp
> node-gyp rebuild

/bin/sh: starting: command not found
gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mitra/git/iiif-image-server-node/node_modules/sharp
gyp ERR! node -v v12.11.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.16.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.16.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mitra/.npm/_logs/2019-12-17T08_44_33_595Z-debug.log
```

**Comment by mitra42** [comment]
Obviously this is a problem in your dependency, but probably something you want to know about.

**Comment by mitra42** [comment]
Just investigating .... sharp installs fine by itself `mkdir foo; cd foo; npm install sharp;` so it appears to be something to do with the dependencies etc, in how iiif-image-server-node is using it.
